### ISSUE TITLE
error: the string is not allowed to refer to a store path.

### ISSUE THREAD

**Issue by philderbeast** [DeterminateSystems/flake-checker#34]
I get the same error message whether I `nix run` or `nix profile install ...`:

```
$ nix run github:DeterminateSystems/flake-checker
error: the string '# This file is automatically @generated by Cargo.
       # It is not intended for manual editing.
       version = 3

       [[package]]
       name = "addr2line"
       version = "0.19.0"
       source = "registry+https://github.com/rust-lang/crates.io-index"
       checksum = "a76fd60b23679b7d19bd066031410fb7e458ccc5e958eb5c325888ce4baedc97"
       dependencies = [
        "compiler_builtins",
        "gimli 0.27.2",
        "rustc-std-workspace-alloc",
        "rustc-std-workspace-core",
       ]

       [[package]]
...
       [[package]]
       name = "zerovec-derive"
       version = "0.9.3"
       source = "registry+https://github.com/rust-lang/crates.io-index"
       checksum = "2154cb6e2a748163354165e22c6a555effb09ca2d16334767bf66bb404f2206e"
       dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.102",
        "synstructure 0.12.6",
       ]
       ' is not allowed to refer to a store path (such as '')
```

```
$ nix --version
nix (Nix) 2.10.3

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

**Comment by philderbeast** [comment]
I got further after upgrading:

```
$ sudo -i nix upgrade-nix
replacing old 'nix-2.10.3'
installing 'nix-2.15.1'

$ nix run github:DeterminateSystems/flake-checker
thread 'main' panicked at 'root node was not a Root node, but was a Fallthrough node', src/flake.rs:178:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lucperkins** [comment]
@philderbeast Could you possibly provide the `flake.lock` that's in the directory in which you ran these commands?

**Comment by aos** [comment]
Running into a similar (same?) issue. Here's the `flake.lock` that I ran it on: https://github.com/aos/flake-templates/blob/master/rust-shell/flake.lock

**Comment by philderbeast** [comment]
> @philderbeast Could you possibly provide the `flake.lock` that's in the directory in which you ran these commands?

[flake.zip](https://github.com/DeterminateSystems/flake-checker/files/11826148/flake.zip).

**Comment by lucperkins** [comment]
@aos I've tried your lockfile locally and didn't have any issues. I'd recommend updating Nix, as your issue may be related to [this](https://github.com/NixOS/nix/pull/7260).

@philderbeast It looks like your `flake.lock` has a structure I haven't seen before (`.nodes.root.inputs.nixpkgs` is an array rather than a string). I'm going to investigate how to handle that properly and update hopefully soon.

**Comment by aos** [comment]
Hi @lucperkins - Looks like it indeed required that I update Nix. Your flake checker found no issues with my flake. Thanks for the heads up!

**Comment by philderbeast** [comment]
Thanks @lucperkins, here's the result of `nix flake lock --recreate-lock-file`:

[recreate-lock-file.zip](https://github.com/DeterminateSystems/flake-checker/files/11827302/recreate-lock-file.zip)
