### ISSUE TITLE
Cannot deal with registry-based lookups of nixpkgs (sometimes)

### ISSUE THREAD

**Issue by lheckemann** [DeterminateSystems/flake-checker#54]
We're getting a failure in https://github.com/DeterminateSystems/nix-to-kubernetes/actions/runs/5552539679/jobs/10140009561?pr=2 because nixpkgs is specified as `nixpkgs.url = "nixpkgs";`. Registry-based references like this should be looked up, and maybe also warned against -- in _my_ opinion they're bad style but I'm not sure we all agree on this.

**Comment by lheckemann** [comment]
The problem happened before the flake update which introduced the local path reference too ;)

**Comment by lheckemann** [comment]
(and it's still the case after your change: https://github.com/DeterminateSystems/nix-to-kubernetes/actions/runs/5579412902/jobs/10195017057 )

**Comment by lucperkins** [comment]
@lheckemann The thing is, I have no idea why this is happening. Running the Flake Checker in that repo works fine and I even ran that `flake.lock` as a test case in the Flake Checker repo. I think it's a spurious error having something or other to do with Actions.

**Comment by lucperkins** [comment]
I'm closing this, as it hasn't been a Flake Checker issue specifically for a while. Once the new release (v0.1.12) is made available via the Action (PR pending), the original issue should be resolved.
